### ISSUE TITLE
Challenge screen list

### ISSUE THREAD

**Issue by ComputerGodJ** [hrollings24/ladder-ios#6]
![image](https://user-images.githubusercontent.com/20072049/109873266-6ef4a500-7c65-11eb-9afc-bf0091a6da90.jpeg)

Pulling down to refresh the challenge list seems to add to the list.  Here, two duplicate instances of the same challenge appeared on launch and refreshing the list keeps adding two more.  Another time, only one appeared initially but the refresh repetition issue occurred.

**Comment by hrollings24** [comment]
fixed in c118d5e
